### ISSUE TITLE
No scrollbar in layer switcher

### ISSUE THREAD

**Issue by paul121** [farmOS/farmOS-map#100]
Appears that this is due to the bump from ol-layerswitcher 3.6 to 3.83. Specifically this change: https://github.com/walkermatt/ol-layerswitcher/commit/d7ff0eabe3c9fbbf8823406b606d19c4cac55c68

If I add this CSS back it works again:

```css
.layer-switcher.shown {
  bottom: 3em;
}
```

Not sure this is really a bug though, their [example](https://github.com/walkermatt/ol-layerswitcher#examples) docs say that scrolling works by setting `max-height` css property. Rather than create an issue upstream I think we can just add our own css for this.

**Comment by mstenta** [comment]
Fixed via #101
