### ISSUE TITLE
farmOS-map packaging and module exports

### ISSUE THREAD

**Issue by symbioquine** [farmOS/farmOS-map#113]
Creating a separate issue since this is related, but not totally the same problem as [#68](https://github.com/farmOS/farmOS-map/issues/68)...

> A little out of band, but wanted to get some recent discussions with @jgaehring and @wgardiner included here (for lack of a better place - maybe this deserves a separate issue)...
> 
> Outside of the farmOS context, we also want to be able to support projects that pull farmOS-map in as a node dependency. Right now, we publish to NPM, but there are some things we're doing that are not ideal:
> 
> - `window.farmOS.map`
> - Consumers of the library need to reference code in `src` directly.
> 
> Field Kit is currently working around this, and SurveyStack (which @wgardiner is working on) will be doing the same.
> 
> One idea that @wgardiner suggested is to create an init function that wraps the logic for creating `window.farmOS.map`, so that it can be optional.
> 
> And @jgaehring mentioned in chat:
> 
> > we should probably export something generic, that can be imported like a regular npm module, and then farmOS can just include a simple JS file that does nothing but attaches it to window
> > then we can figure out how to make Morgan's optimizations work best with that setup (and hopefully, such a setup will only make his optimizations easier, too)
> 
> @symbioquine what are your thoughts on these points, and how do they relate to these proposed changes? I know that the `window.farmOS.map` piece is already changing, but would an init function make sense too? And if we don't have a global, what does that mean for node-based apps using behaviors?

_Originally posted by @mstenta in https://github.com/farmOS/farmOS-map/issues/68#issuecomment-844253033_

**Comment by symbioquine** [comment]
> > A little out of band, but wanted to get some recent discussions with @jgaehring and @wgardiner included here (for lack of a better place - maybe this deserves a separate issue)...
> > Outside of the farmOS context, we also want to be able to support projects that pull farmOS-map in as a node dependency. Right now, we publish to NPM, but there are some things we're doing that are not ideal:
> > ```
> > * `window.farmOS.map`
> > 
> > * Consumers of the library need to reference code in `src` directly.
> > ```
> 
> Thanks for bringing this up! I was trying to figure out when to work it into the discussion, but didn't want to distract from the `ol.js`/Federation question.
> 
> I **do** think that addressing how farmOS-map is packaged/exposed would be an auspicious thing to change as part of the 2.x major version since it necessarily involves breaking changes.
> 
> > > we should probably export something generic, that can be imported like a regular npm module, and then farmOS can just include a simple JS file that does nothing but attaches it to window
> > > then we can figure out how to make Morgan's optimizations work best with that setup (and hopefully, such a setup will only make his optimizations easier, too)
> > 
> > 
> > @symbioquine what are your thoughts on these points, and how do they relate to these proposed changes? I know that the `window.farmOS.map` piece is already changing, but would an init function make sense too? And if we don't have a global, what does that mean for node-based apps using behaviors?
> 
> I don't have a ready answer other than that I'm excited to brainstorm with you folks to see if we can find a more coherent approach...
> 
> One thought is that by changing `farmOS-map/src/main.js` to have a default export, we make it possible for code created with other bundlers and/or targeting non-browser environments to do something like this;
> 
> ```js
> import farmOSMap from 'farmOS-map/main';
> 
> farmOSMap.behaviors.myAwesomeBehavior = {
>   attach(instance) {
>     ...
>   },
> };
> ```
> 
> Of course, it's arguably a bad idea to mutate the things you import since that's akin to global state/variables. It might make sense for us to look at what plugin models [isomorphic JS libraries](https://en.wikipedia.org/wiki/Isomorphic_JavaScript) are using. Maybe we can learn something from those...
> [...]

_Originally posted by @symbioquine in https://github.com/farmOS/farmOS-map/issues/68#issuecomment-844347893_

**Comment by symbioquine** [comment]
We had some really good discussion about this on the Thursday (2021/05/20) dev call.

The idea that sounded most promising during that discussion was to create a new class `MapInstanceManager` (I'm not a big fan of naming things "managers", but I don't have a better suggestion right now.) at `./src/MapInstanceManager.js` where the fields on that class match those which are currently on `window.farmOS.map`. Then update `./src/main.js` to create an instance of `MapInstanceManager` assigned to `window.farmOS.map`.

This would also have the following benefits;

* Retains backwards compatibility with the current API and still allows a known location that behaviors can register themselves.
* Allows applications to ignore `window.farmOS.map` in scenarios where that global mutable state is not helpful.
* Allows applications to control the lifecycle of their own `MapInstanceManager` objects - e.g. for cases where the same "page" needs to register different default behaviors for different map instances.
* Allows for easier testing of different combinations of default behaviors.

Another aspect we should consider is whether to include the `.src/` directory in the NPM package - [as it is now](https://unpkg.com/browse/@farmos.org/farmos-map@1.4.2/) - or produce a simplified version of the source tree in the root of the package to facilitate cleaner `import` statements - as [OpenLayers does](https://unpkg.com/browse/ol@6.5.0/). This would allow some consumers to access `farmOS-map` like this;

```js
import MapInstanceManager from 'farmos-map/MapInstanceManager';

const maps = new MapInstanceManager();

const map = maps.create('my-map');
```

**Comment by symbioquine** [comment]
@wgardiner I think you were one of the other stakeholders here... Any chance you can take a look and see if the above linked changes fully address your use-case?

**Comment by mstenta** [comment]
I think we can close this now that #116 and #117 are merged. Do you agree @symbioquine ?

**Comment by symbioquine** [comment]
Yep :)
