### ISSUE TITLE
Publish GitHub Pages preview on tagged release

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS-map#136]
We have a GitHub Actions workflow for packaging tagged releases. Let's add a step to this to automatically update the preview that we publish on GitHub Pages at https://farmos.github.io/farmOS-map/ - which is outdated now.

**Comment by mstenta** [comment]
For reference, we use the `peaceiris/actions-gh-pages@v3` action to do this in the farmOS 2.x branch, for publishing https://docs.farmos.org: https://github.com/farmOS/farmOS/blob/9e7598955cba3c1ada06624366a650766d1338a3/.github/workflows/publish-docs.yml#L26

**Comment by symbioquine** [comment]
I think this is a duplicate of https://github.com/farmOS/farmOS-map/issues/74 I'm happy to own making this change so I'll assign that issue to myself and close this one now.

**Comment by mstenta** [comment]
Ah yes oops! Thanks @symbioquine :-)
