### ISSUE TITLE
Bump OL to 6.9

### ISSUE THREAD

**Issue by paul121** [farmOS/farmOS-map#142]
There have been some significant OL releases since 6.5: https://github.com/openlayers/openlayers/releases

Aside from bug fixes there are some notable improvements I'm interested in, but might require additional imports to include in farmOS-map. As a first step we should just bump the version, but are there any other considerations?

Cool features:
- 6.6 New WKB source
- 6.7 New GeoTIFF source (uses a WebGL renderer, might improve Mapbox layers as well?)
- 6.8 Improved vector tile rendering

**Comment by mstenta** [comment]
Sounds good to me!
