### ISSUE TITLE
Improve the map icon svgs

### ISSUE THREAD

**Issue by gbathree** [farmOS/farmOS-map#146]
Based on feedback we've got in using the library, the existing icons while clean are not clear enough.  I've reviewed these with quite a few people and we ended up on these particular ones.  

I'm not 100% sure of the svg structure needed to submit successfully, so someone will need to test this out and report back if it shows the correct green color (I made it black and white basically, assuming the color will get replaced in the browser (?)).

![create-area](https://user-images.githubu
![edit](https://user-images.githubusercontent.com/1742369/160290259-0b9e7c99-7faf-4a61-b29b-a17158213165.svg)
![edit-optimized](https://user-images.githubusercontent.com/1742369/160290260-7819647d-de25-4646-980d-a907df14c7a4.svg)
![create-point-optimized](https://user-images.githubusercontent.com/1742369/160290258-54601c9b-b5de-47e5-9783-a6748f200b4a.svg)ercontent.com/1742369/160290250-ac19b953-acc9-42b7-82d4-d5e99c58e80e.svg)
![create-area-optimized](https://user-images.githubusercontent.com/1742369/160290251-dbfdcc9c-4de8-42db-8c99-067ad23d4965.svg)
![create-circle](https://user-images.githubusercontent.com/1742369/160290252-98ea3fd4-80b4-4845-ba8f-12d52ecb7ba5.svg)
![create-circle-optimized](https://user-images.githubusercontent.com/1742369/160290253-5a809b04-aa0a-4555-aeb1-30a3af660ec0.svg)
![create-line](https://user-images.githubusercontent.com/1742369/160290254-23136a7a-5156-4bf7-a996-b682e742d7f4.svg)
![create-line-optimized](https://user-images.githubusercontent.com/1742369/160290255-37d1722a-91ec-49b5-8504-2713faf963e5.svg)
![create-point](https://user-images.githubusercontent.com/1742369/160290257-b665429a-a38f-4e31-9bfe-af8227a0edb0.svg)

**Comment by symbioquine** [comment]
The current PR for this issue is #179

**Comment by symbioquine** [comment]
#179 has been merged and is included in the latest farmOS-map release.
