### ISSUE TITLE
Consider making snapping grid optional

### ISSUE THREAD

**Issue by paul121** [farmOS/farmOS-map#158]
A couple discussions lately have highlighted the complexity of the farmOS UI. I think this is in part due to the quantity and complexity of the available features! One example is the snapping grid when using the editing controls on the map.

For someone that is new and learning how to use the map drawing tool this is just another icon on the screen that when clicked starts a complicated UI/UX that is confusing to turn off. I'm curious if we could consider making this an optional or "opt-in" feature, similar to how the map side panel added with https://github.com/farmOS/farmOS-map/issues/14 can be turned on/off with a setting in farmOS.

Would a setting for the snapping grid to the map settings in farmOS require any changes to farmOS-map itself? I believe the snapping grid control is more intertwined with the map edit behavior so it's not as simple as replicating the side panel behavior in farmOS core: https://github.com/farmOS/farmOS/blob/2.x/modules/core/map/js/farmOS.map.behaviors.enable_side_panel.js

**Comment by mstenta** [comment]
Here is where the snapping grid behavior is being added (thanks @symbioquine for pointing that out on today's dev call): https://github.com/farmOS/farmOS/blob/04bf771d91cde8276b67090d2b97c4e4558332b9/modules/core/map/js/farmOS.map.behaviors.wkt.js#L39

**Comment by symbioquine** [comment]
Since the snapping grid is already optional farmOS-map behavior, I think we can close this. I could see a follow-up in farmOS to make enabling the snapping grid opt-in - maybe a site-wide configuration and/or per-user setting in the side-panel.
