### ISSUE TITLE
Fix color scheme compliance of remaining icons

### ISSUE THREAD

**Issue by symbioquine** [farmOS/farmOS-map#181]
This is a follow-up from the existing color scheme issues observed as part of https://github.com/farmOS/farmOS-map/pull/179#issuecomment-1255225533

![image](https://user-images.githubusercontent.com/30754460/191792618-f908e7b3-bae6-4650-93b5-8ef6191533d1.png)

The geolocate and layers icons should be pink.

**Comment by paul121** [comment]
This is technically a farmOS core issue but I've opened #186 which makes it easier for code integrating farmOS-map to have consistent accent colors.
