### ISSUE TITLE
Measure behavior breaks modify interaction under certain circumstances

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS-map#195]
A strange bug was encountered with the edit behavior's modify interaction, specifically after the edit layer's features are changed, for example by pasting WKT text into farmOS's data field under the map, which is a new feature provided by this PR: https://github.com/farmOS/farmOS/pull/670

After pasting the WKT, if you click the "Modify" button, then click on a feature in the map, then attempt to drag one of its vertices, the vertex point itself moves, but the shape itself doesn't change. If you release the click, and then try to move the same vertex again, it works as expected.

In testing, @symbioquine @paul121 and myself narrowed it down to the measure behavior that is added by farmOS's WKT behavior here: https://github.com/farmOS/farmOS/blob/2b3bb21683396fc0b5ec0cd2f5107dc4e4e4d16a/modules/core/map/js/farmOS.map.behaviors.wkt.js#L44

Commenting out that line (omitting the measure behavior) fixes the issue. So it seems that something within the measure behavior's logic is causing this.

**Comment by mstenta** [comment]
Copying some of @symbioquine's thoughts from chat:

> I suspect one of the issues is that [this code](https://github.com/farmOS/farmOS-map/blob/73a597c9ffdf4b43545975c27f858cbb60cf587a/src/behavior/measure.js#L140-L150) uses farmOS-map "events" instead of watching the vector layer for changes more directly...
> I think that means that you change the features without causing a "drawstart", "drawend", "modifystart"; it will be somewhat broken.

https://irc.farmos.org/bot/log/farmOS/2023-05-09#T89925

**Comment by symbioquine** [comment]
There's actually two related issues here;

1. The modify geometry functionality breaks
2. The old measure overlays are not cleaned up when the layer is cleared

[2023_05_11_farmOS-map_measure_behaviour_issue_further.webm](https://github.com/farmOS/farmOS-map/assets/30754460/0734267e-da08-4a4a-9b8b-ab52415a7c5e)

I was originally proposing a rewrite of the measure behaviour to fix it more broadly, but I think a more restrained approach makes sense first...

The smallest change we need to do to fix the measure behaviour and the modify geometry bug is;

```diff
--- a/src/behavior/measure.js
+++ b/src/behavior/measure.js
@@ -134,6 +134,14 @@ export default {
       createMeasure(feature);
     });
 
+    layer.getSource().on('clear', () => {
+      stopMeasure();
+    });
+
+    layer.getSource().on('addfeature', (evt) => {
+      startMeasure(evt.feature);
+    });
+
     // If the instance has an Edit control, attach listeners to the map
     // interactions so that we can apply measurements to the features.
     if (instance.edit) {
```

[2023_05_11_farmOS-map_measure_behaviour_issue_with_fix.webm](https://github.com/farmOS/farmOS-map/assets/30754460/0597e90a-0055-4903-8974-066a3ae6e27b)

We'll still need to do a bit more serious change if we want measure to work correctly for multiple map instances - involving moving the global state onto the map instance somehow. See #84 and #94
