### ISSUE TITLE
Map Search Bar no longer generating results

### ISSUE THREAD

**Issue by gbathree** [farmOS/farmOS-map#197]
**Describe the bug**
Search bar in farmOS Map is no longer working.  Tested in coffeeshop.farmos.net and another instance (both managed by Farmier).  When you attempt to search it reports "Error!  No Internet Connection?".   I think this is an everywhere issue and should be quickly repeatable.  It appears maybe (based on the console log, see below) that this may be a change in CORS policies for the API which would normally return the search results (?).

**Expected behavior**
Should search and find addresses.

**Screenshots**

![image](https://github.com/farmOS/farmOS-map/assets/1742369/4322b87c-f52b-45e3-a0a2-90e09a7809ab)

This was tested in firefox (ubuntu) and probably chrome (windows), but I think this isn't a browser or OS issue.

**Additional context**

**Comment by paul121** [comment]
I believe this is the issue: https://github.com/osm-search/Nominatim/issues/3134

The public Nominatim Geocoding API server recently updated/was completely rewritten and introduced this change: https://github.com/osm-search/Nominatim/releases/tag/v4.3.0

Our ol-geocoding dependency needs to be updated for the currect URL path.

**Comment by mstenta** [comment]
Good catch @gbathree and @paul121! It looks like this has been fixed in `ol-geocoder`: https://github.com/Dominique92/ol-geocoder/pull/268

We may just need to update our NPM packages and publish a new release.
