### ISSUE TITLE
Add ability to use custom stroke colors

### ISSUE THREAD

**Issue by peacog** [farmOS/farmOS-map#201]
Currently if we want to use stroke colors other than the 8 predefined named colors it's necessary to write a style function. It would be great if we could simply pass the hex or rgb value in the color option of the addLayer method. I've created a PR that does that. The color option can be one of the predefined color names, a hex value with or without alpha channel, or an rgb() or rgba() value.

Here's the PR https://github.com/farmOS/farmOS-map/pull/200

This is an enhancement rather than a bug, but I don't have permission to change the label :)

**Comment by symbioquine** [comment]
Thanks @peacog! Label updated and replied on PR

**Comment by symbioquine** [comment]
This change has been merged.
