### ISSUE TITLE
Ability to add own WMS layers

### ISSUE THREAD

**Issue by Skipper-is** [farmOS/farmOS-map#25]
The ability to add your own WMS/WFS/WMTS layers would be really helpful, and would allow you to bring in basemaps from a variety of external sources.
[Example of WMS Layer through OpenLayers](https://openlayers.org/en/latest/examples/wms-tiled.html)
And the API reference:
[Tiled WMS](https://openlayers.org/en/latest/apidoc/module-ol_source_TileWMS-TileWMS.html)
This is for tiled WMS, can also implement single image

**Comment by mstenta** [comment]
This is already possible! :-)

Here is the commit that added a `addWMSTileLayer()` function: https://github.com/farmOS/farmOS-map/commit/d5595f29f4f01617c2a50775a05c820670c01596

And take a look at this issue for reference: https://github.com/farmOS/farmOS-map/issues/16

The NRCS module that is included with farmOS is going to be adapted to inject it's own layers into the map (from a WMS source). I already have it working in the `farmOS-map` branch of my farmOS fork: https://github.com/farmOS/farmOS/commit/2e8ab33e1aac6332e27679c0063291af4ca0b898

It does this by simply adding the following JavaScript to the page that has farmOS-map:

```
(function () {
  farmOS.map.behaviors.farm_soil_nrcs = {
    attach: function (instance) {
      var title = 'NRCS Soil Survey';
      var url = 'https://sdmdataaccess.nrcs.usda.gov/Spatial/SDM.wms';
      var params = {
        LAYERS: 'MapunitPoly',
        VERSION: '1.1.1',
      };
      var visible = false;
      instance.addWMSTileLayer(title, url, params, visible);
    }
  };
}());
```

This means that it will be super easy for farmOS modules to add their own layers, simply by adding a JavaScript file to the page.

And in the farmOS Field Kit context, @jgaehring is working on integrating farmOS-map into the app right now - so he'll be figuring out the best way to implement things there as well.
