### ISSUE TITLE
Return the layer object from add*Layer methods?

### ISSUE THREAD

**Issue by jgaehring** [farmOS/farmOS-map#27]
I'm playing around with how to modify my map in response to user interactions in Field Kit.

I found it useful to add a return statement to the `addWKTLayer` method, like so:

```js
  addWKTLayer(title, wkt, color, visible = true) {
    // ...
    const layer = new VectorLayer({
      title,
      source,
      style,
      visible,
    });
    this.map.addLayer(layer);
    return layer;
  },
```

That way I can call it like this, storing the layer in state, when my component mounts:

```js
this.layers.wkt = this.map.addWKTLayer("wkt", this.wkt, "orange");
```

and then when my component updates, remove it, and replace it with the new data:

```js
this.map.map.removeLayer(this.layers.wkt);
this.layers.wkt = this.map.addWKTLayer("movement", this.wkt, "orange");
```

I'm not sure if this is the best way to handle layer transformations, but it seemed to me like the easiest, without adding more elaborate methods to the library. Curious what your thoughts are, @mstenta. It seems simple enough to add such a return statement, potentially to all our "add*Layer" methods, but is that how we want the library to be used?

**Comment by mstenta** [comment]
Yea that makes sense to me!
