### ISSUE TITLE
Use SVG icons instead of Unicode characters for drawing control buttons

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS-map#41]
This is a follow up to #18 and #40

The drawing control buttons are currently represented with the following unicode characters:

- Point: &#11039; (\u2B1F)
- Line: &#9472; (\u2500)
- Polygon: &#8226; (\u2022)
- Select/move/modify: &#9997; (\u270d)
- Delete: &#10006; (\u2716)

They're ok... best we could find in Unicode.

Providing our own SVGs will be a good next step, and will allow us more flexibility to make the buttons intuitive.

**Comment by mstenta** [comment]
Relevant comment from https://github.com/farmOS/farmOS-map/issues/40:

> 
> - The "X" button communicates "Exit drawing mode" to me. But it's actually a Delete button, so I'd make it a trash can
> - The Line button looks like a minus sign, when I look at it I would assume it deletes a point in a polygon. I'd switch the icon to more like a "/" with dots at endpoints

**Comment by mstenta** [comment]
Hey while we're at it maybe we can do the Geolocate button as well? :-)

Currently it is using this unicode character: &#9678;

**Comment by mstenta** [comment]
FWIW, this is what the Geolocate button looked like in farmOS years ago: https://git.drupalcode.org/project/openlayers_geolocate_button/blob/7.x-1.x/includes/behaviors/openlayers_behavior_geolocate_button.png

I still like that design. We converted to unicode characters with Openlayers 3.x migration to follow convention.

**Comment by jgaehring** [comment]
I've been using the free Material Design icon set for Field Kit to date, and I like some of the options it provides for drawing etc.

For drawing a line:
https://material.io/resources/icons/?icon=timeline&style=baseline

For drawing a polygon (not so sure about this one, maybe we keep the unicode char instead):
https://material.io/resources/icons/?icon=category&style=baseline

For freehand drawing, if we choose to add that:
https://material.io/resources/icons/?icon=gesture&style=baseline

For modifying geometries (we could probably remove the "A" from the middle if desired):
https://material.io/resources/icons/?icon=format_shapes&style=baseline

For translation:
https://material.io/resources/icons/?icon=open_with&style=baseline

For the Geolocate button:
https://material.io/resources/icons/?icon=my_location&style=baseline

And if we want to add the feature to drop a point at your location, perhaps this:
https://material.io/resources/icons/?icon=room&style=baseline

**Comment by mstenta** [comment]
I like all of those!

The "modifying geometries" one is the only one I'm unsure about (https://material.io/resources/icons/?icon=format_shapes&style=baseline).

But maybe first we should decide if we want to separate the select/modify/move interactions, and have buttons for each.

**Comment by jgaehring** [comment]
I guess there's also the question of whether we use SVG or PNG files. I usually opt for SVG for performance and styling purposes, but PNG might be easier.

If we go with SVG, I imagine we'll just set the innerHTML of our button with the SVG markup as a string or template literal, which shouldn't be too much harder. Then we can style the svg tag's fill property et al for things like graying out the button if it's disabled or inactive or what have you.

**Comment by jgaehring** [comment]
> But maybe first we should decide if we want to separate the select/modify/move interactions, and have buttons for each.

Oh yea, I was going on that assumption. Perhaps if we just wanted to replace the current select/modify/move icon we have now, we could go with something like this: https://material.io/resources/icons/?icon=edit&style=baseline

**Comment by mstenta** [comment]
> Perhaps if we just wanted to replace the current select/modify/move icon we have now, we could go with something like this

I like that!

> I'm also thinking that the conversion to SVG could be done simultaneously with separating the those functions, but perhaps that's a bit to ambitious.

Ah ok - I tend to always try to think of things as separate, even if they happen one right after another. So first step I think should be replace current icons (with the focus being simply on figuring out all the SVG, CSS details, etc), followed by splitting up the button and changing the icon (with the focus being on deciding how those buttons work).

**Comment by jgaehring** [comment]
> I tend to always try to think of things as separate, even if they happen one right after another. 

Yea, good call.

**Comment by mstenta** [comment]
We might want to look at the button color scheme at the same time: https://github.com/farmOS/farmOS-map/issues/43

Currently, we have white text on blue background. If we want to change the color scheme, it might affect what color the SVGs are?

**Comment by jgaehring** [comment]
I did a little experimenting with this at the end of last week.

I created a codesandbox to test out the idea mentioned above, in https://github.com/farmOS/farmOS-map/issues/41#issuecomment-535128931, to just set the `innerHTML` for the targeted DOM node: https://codesandbox.io/s/svg-icons-for-farmos-map-nmrbd

I also did another little experiment on https://mstenta.github.io/farmOS-map/, just playing around in the console, to replace the search icon. To reproduce, just open up the console, and run the following:

```js
const gcdBtn = document.getElementById('gcd-button-control');
gcdBtn.innerHTML = `
  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
    <path d="M22 11h-4.17l3.24-3.24-1.41-1.42L15 11h-2V9l4.66-4.66-1.42-1.41L13 6.17V2h-2v4.17L7.76 2.93 6.34 4.34 11 9v2H9L4.34 6.34 2.93 7.76 6.17 11H2v2h4.17l-3.24 3.24 1.41 1.42L9 13h2v2l-4.66 4.66 1.42 1.41L11 17.83V22h2v-4.17l3.24 3.24 1.42-1.41L13 15v-2h2l4.66 4.66 1.41-1.42L17.83 13H22z"/>
    <path fill="none" d="M0 0h24v24H0z"/>
  </svg>
`
```

Then you still need to remove the old icon, which can be done by adding this to the CSS:

```css
.ol-geocoder .gcd-gl-btn:after {
    display: none;
}
```

You can also modify the `fill` properties of the new SVG element with the following CSS:

```css
#gcd-button-control > svg {
    fill: cornflowerblue;
}
```

The result is:

![image](https://user-images.githubusercontent.com/5556545/75175967-486e6680-5701-11ea-99b4-871d10de05f1.png)

**Comment by mstenta** [comment]
I took a first pass at this, and it's looking pretty good already!

![Screenshot from 2020-02-24 22-31-41](https://user-images.githubusercontent.com/95381/75212644-8bf2c000-5755-11ea-9bd5-79ab9e1086c3.png)

I used most of your original suggestions @jgaehring, except I used a square for the polygon button instead of the three shapes one. And I was able to successfully remove the "A" from the "Modify features" button.

Only one thing left to figure out: it seems that the SVGs in the Edit buttons are blocking click events from reaching the button elements below them.  So none of the buttons work.  The exception is the Geolocate button, which DOES work. So there must be some difference between those two implementations...

**Comment by mstenta** [comment]
> Only one thing left to figure out: it seems that the SVGs in the Edit buttons are blocking click events from reaching the button elements below them.

Fixed with `pointer-events: none` CSS rule on the SVG elements.

**Comment by jgaehring** [comment]
Oh these all look great!!!

> Fixed with pointer-events: none CSS rule on the SVG elements.

Ah! I was just looking at the docs on that. Glad it worked!

**Comment by mstenta** [comment]
This is done! Thanks for all the help and ideas @jgaehring !
