### ISSUE TITLE
Measure lines and polygons in the drawing layer

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS-map#47]
Basically replicate this OpenLayers example: https://openlayers.org/en/latest/examples/measure.html

**Comment by mstenta** [comment]
Pushed a work-in-progress commit to a new `measure` branch in my fork: https://github.com/farmOS/farmOS-map/commit/d0da815308e31d0086b49b13cab6b895b9a8a56b

This replicates the essential logic of the OpenLayers example. It works to calculate length and area when you are drawing new shapes.

There are some things it does NOT do yet - so these are the next steps:

- Update measurements when shapes are modified/moved.
- Use the map instance's system of measurement.
- Show large measurements in acres/hectares, small measurements in ft<sup>2</sup>/m<sup>2</sup> (replicate logic currently in farmOS).
- Show measurements when initial shapes are loaded in to the map (eg: when we edit existing shapes in farmOS).

Maybe others...

**Comment by mstenta** [comment]
Question: if the draw interaction is disabled before `drawend` fires, does the `listener` get deactivated?

**Comment by mstenta** [comment]
I have a tentative merge commit ready for this. Hoping to bang on it a little more before pushing to origin. But in general it seems to be working well!

**Comment by mstenta** [comment]
Test it out here: https://mstenta.github.io/farmOS-map/

**Comment by jgaehring** [comment]
I haven't been able to break this. Have you merged it into master yet? Can't wait to push it out in FK v0.4.9!

**Comment by mstenta** [comment]
Merged and v0.6.0 released!

https://github.com/farmOS/farmOS-map/releases/tag/v0.6.0
