### ISSUE TITLE
Add ability to delete vertices

### ISSUE THREAD

**Issue by jgaehring** [farmOS/farmOS-map#54]
From https://github.com/farmOS/farmOS-map/issues/40#issuecomment-535114650:

> Playing around with modifying features makes me think that we'll definitely want the ability to remove vertices, too. I wound up with a really funky geometry because when I thought I was tapping on a vertex to move it, I ended up creating a new vertex instead. Wound up with a really jagged shape in the end, with a lot of unnecessary points.

**Comment by mstenta** [comment]
Somewhat related, although probably separate: #52

**Comment by jgaehring** [comment]
> Somewhat related, although probably separate: #52 

Ah yes, having an undo button could make this issue moot.

**Comment by mstenta** [comment]
Ah true - good point. Maybe there isn't really a need to delete vertices in the *middle* of a shape... just ones that were added on the end. Well we can leave this open and see if anyone else thinks it would be useful.

**Comment by jgaehring** [comment]
Sounds good to me!

**Comment by symbioquine** [comment]
This already exists. You hold down the `ALT` key and click on the vertex after selecting the polygon/polyline with the edit tool;

![2022_05_12_demonstrating_vertex_deletion](https://user-images.githubusercontent.com/30754460/168201490-60db5d24-b287-44d1-b72c-d9b7a9e94b0d.gif)

*That popover saying "0 Item(s)" is a little ugly, but other than that I don't see anything we need to do here.*
