### ISSUE TITLE
Add Babel

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS-map#61]
We are not currently using Babel to transpile for older browsers. Let's consider adding this for v1.0.0. (cc @jgaehring)

**Comment by mstenta** [comment]
I am leaning towards deferring this until there is a reported need for it.  It's an easy addition, but I haven't seen a direct need for it yet.

We already use Webpack to package ES6 modules into a single `farmOS-map.js` file, and farmOS-map is working already in modern Chrome and Firefox, probably others. I don't think we're using any bleeding edge features that necessitate additional transpiling. And in general, we don't have a policy for supporting outdated browsers in farmOS upstream.

So unless we hear that something is broken in a common browser and Babel is the solution, or we need new JS code features that are not fully supported yet, I'm going to close this as "Won't Fix."

**Comment by jgaehring** [comment]
Sounds good to me! :+1:
