### ISSUE TITLE
layer for Emilia-Romagna northern Italy soil information

### ISSUE THREAD

**Issue by bonushenricus** [farmOS/farmOS-map#70]
Hello
a little modification over map norway
to create a layer with the soil information in region Emilia-Romagna, where I live. I attach the folder in this issues: [farm_map_em_rom-7.x-1.x.zip](https://github.com/farmOS/farmOS-map/files/4460943/farm_map_em_rom-7.x-1.x.zip)
I try also to add a layer with the wms map of the cadastre of the entire Italy, but it doesn't run: I believe is a projection problem.

Enrico Gabrielli

**Comment by mstenta** [comment]
I see that the WMS URL is `http://servizigis.regione.emilia-romagna.it/wms/suoli` - but when I try to visit that address in a browser I am prompted to enter a username and password. Perhaps that is part of the problem?

**Comment by bonushenricus** [comment]
No problem, Mike!
This is an issues, simple, to tell you that's runs! In my localhost the new model farm_map_em_rom runs! Sure, if you don't know where the Emilia-Romagna is it's a bit difficult to see the result, because the soil informations are view at a scale minimum of 1:30'000. And the wms is open, without username and password.

**Comment by mstenta** [comment]
Oh! I misunderstood. :-)

That's great @bonushenricus ! You should consider creating your own GitHub repo for it (like the author of the Finland maps module: https://github.com/rkioski/farm_map_fi)

Then we can put a link to it here: https://farmos.org/development/projects/#other-modules

I am going to close this issue. Thanks for sharing!
